### ISSUE TITLE
'WebDriver' object has no attribute 'find_element_by_id'

### ISSUE THREAD

**Issue by colinbouvry** [AkshaySiwal/LinkedIn_networking#11]
`C:\dev\LinkedIn_networking>python linkedIn.py
C:\dev\LinkedIn_networking\linkedIn.py:55: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(ChromeDriverManager().install())

DevTools listening on ws://127.0.0.1:60722/devtools/browser/87b1c9f2-a2e0-4a63-84d5-3d4b1275d8c3
Traceback (most recent call last):
  File "C:\dev\LinkedIn_networking\linkedIn.py", line 57, in <module>
    driver.find_element_by_id('username').send_keys(parameters.linkedin_username)
AttributeError: 'WebDriver' object has no attribute 'find_element_by_id'`

**Comment by AkshaySiwal** [comment]
Fixed. Sorry for the delay.
