### ISSUE TITLE
Separate settings from code

### ISSUE THREAD

**Issue by metaperl** [AkshaySiwal/LinkedIn_networking#3]
Instead of editing the source code to configure the program, an external file for the settings is ideal. This way, credentials never accidentally get committed. And updates to the code dont affect the credentials.

I personally like Pydantic Settings to handle settings but Dynaconf is another popular option. Configobj also deserves mention.

**Comment by AkshaySiwal** [comment]
@metaperl Code picks creds from a separate config file (parameter.py). Will add parameter.py to git ignore to avoid accidental push. 
Closing this issue as this is more of a feature request.
