### ISSUE TITLE
Corporate environment not able to access the chromedriver.exe

### ISSUE THREAD

**Issue by sandeepnegi1996** [AkshaySiwal/LinkedIn_networking#5]
Hi Akshay,

I am in a corporate environment and the code is not able to access the chromedriver for me , to rectify this issue what I did I have stored the chromedriver in the same project directory and then gave that chromedriver to the program,

I want to make a pull request for the same

**Comment by AkshaySiwal** [comment]
Please check your PATH environment variable to fix it.
